routes/admin.php
<?php

use App\Http\Controllers\Admin\BlogsController;
use App\Http\Controllers\Admin\BookingsController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\FaqsController;
use App\Http\Controllers\Admin\InquiresController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\PackageCategoriesController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\ScheduleController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function () {
    Auth::routes();

    Route::post('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::get('/profile', [App\Http\Controllers\HomeController::class, 'profile'])->name('profile')->middleware('auth');

    Route::resource('locations', LocationController::class)->middleware('auth');
    Route::resource('cms', CmsController::class)->middleware('auth');
    Route::resource('faqs', FaqsController::class)->middleware('auth');
    Route::resource('inquires', InquiresController::class)->middleware('auth');
    Route::resource('package_categories', PackageCategoriesController::class)->middleware('auth');
    Route::resource('packages', PackagesController::class)->middleware('auth');
    Route::resource('schedule', ScheduleController::class)->middleware('auth');
    Route::resource('bookings', BookingsController::class)->middleware('auth');
    Route::resource('blogs', BlogsController::class)->middleware('auth');

    Route::post('fetch-states', [LocationController::class, 'fetchState'])->middleware('auth');
    Route::post('fetch-cities', [LocationController::class, 'fetchCity'])->middleware('auth');

    Route::get('slug', [CmsController::class, 'slug'])->name('slug')->middleware('auth');

    Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password')->middleware('auth');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Http/Controllers/Admin/CmsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CmsPage;
use Illuminate\Http\Request;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Support\Str;

class CmsController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $cmsPages = CmsPage::orderBy('created_at', 'desc')->get();
        return view('admin.Cms.index', compact('cmsPages'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        return view('admin.Cms.create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'title' => 'required',
                'slug' => 'required',
                'content' => 'required',
            ]);
            
            CmsPage::create($request->post());

            return redirect()->route('cms.index')->with('success','page has been created successfully.');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\CmsPage  $company
    * @return \Illuminate\Http\Response
    */
    public function edit(CmsPage $cm)
    {
        return view('admin.Cms.edit',compact('cm'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\CmsPage  $location
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, CmsPage $cm)
    {
        try {
            $request->validate([
                'title' => 'required',
                'slug' => 'required',
                'content' => 'required'
            ]);
            
            $cm->fill($request->post())->save();

            return redirect()->route('cms.index')->with('success','Page Has Been updated successfully');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\CmsPage  $cms
    * @return \Illuminate\Http\Response
    */
    public function destroy(CmsPage $cm)
    {
        try {
            $cm->delete();
            return redirect()->route('cms.index')->with('success','Page has been deleted successfully');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }


    /**
     * 
     * genrate slug by title
     */
    public function slug(Request $request)
    {
        $slug = Str::slug($request->title, '-');
        return response()->json(['slug' => $slug]);
    }
}

resources/views/admin/Cms/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="edit">
                            <h5>Create Page</h5><hr>
                            <form method="post" action="{{ route('cms.store') }}">
                                @csrf
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="title">Title</label>
                                        <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title">
                                        @if($errors->has('title'))
                                            <div class="error"><b>{{ $errors->first('title') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label for="slug">Slug</label>
                                        <input type="text" name="slug" value="{{ old('slug') }}" class="form-control" id="slug" placeholder="Slug" readonly>
                                        @if($errors->has('slug'))
                                            <div class="error"><b>{{ $errors->first('slug') }}</b></div>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="content">Content</label>
                                        <textarea name="content" id="content"></textarea>
                                    </div>
                                </div>
                                
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a type="button" href="{{ route('cms.index') }}" class="btn btn-danger">Back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content');
</script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
    $("#title").on("keyup change", function(e) {
        $.get('{{ route("slug") }}',
            { 'title': $(this).val() },
            function( data ) {
            $('#slug').val(data.slug);
            }
        );
    });
</script>
@endsection

resources/views/admin/Cms/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="edit">
                            <h5>Create Page</h5><hr>
                            <form method="post" action="{{ route('cms.update', $cm->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="title">Title</label>
                                        <input type="text" name="title" value="{{ $cm->title ?? "" }}" class="form-control" id="title" placeholder="Title">
                                        @if($errors->has('title'))
                                            <div class="error"><b>{{ $errors->first('title') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label for="slug">Slug</label>
                                        <input type="text" name="slug" value="{{ $cm->slug ?? "" }}" class="form-control" id="slug" placeholder="Slug" readonly>
                                        @if($errors->has('slug'))
                                            <div class="error"><b>{{ $errors->first('slug') }}</b></div>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="content">Content</label>
                                        <textarea name="content" id="content">{{ $cm->content ?? "" }}</textarea>
                                    </div>
                                </div>
                                
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a type="button" href="{{ route('cms.index') }}" class="btn btn-danger">Back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content');
</script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
    $("#title").on("keyup change", function(e) {
        $.get('{{ route("slug") }}',
            { 'title': $(this).val() },
            function( data ) {
            $('#slug').val(data.slug);
            }
        );
    });
</script>
@endsection

resources/views/admin/Cms/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row mt-3">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3"><h5 class="card-title">CMS Pages</h5></div>
                            <div class="col-lg-9" style="padding: 15px"><a href="{{ route('cms.create') }}" class="btn btn-warning" style="float: right;">Create Cms Page</a></div>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr class="th_color">
                                        <th scope="col"><b>#</b></th>
                                        <th scope="col"><b>Title</b></th>
                                        <th scope="col"><b>Slug</b></th>
                                        <th scope="col"><b>Content</b></th>
                                        <th scope="col"><b>Action</b></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if(count($cmsPages) > 0)
                                        @foreach($cmsPages as $cms)
                                            <tr>
                                                <th scope="row">{{ $cms->id }}</th>
                                                <td>{{ $cms->title ?? "" }}</td>
                                                <td>{{ $cms->slug ?? "" }}</td>
                                                <td style="max-width: 900px; overflow: hidden;">{{ $cms->content ?? "" }}</td>
                                                <td>
                                                    <form action="{{ route('cms.destroy',$cms->id) }}" method="Post">
                                                        <a class="btn btn-primary" href="{{ route('cms.edit',$cms->id) }}">Edit</a>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('Do you want to delete this page?')" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <th scope="row"></th>
                                            <td></td>
                                            <td></td>
                                            <td>No CMS Pages Found!...</td>
                                            <td></td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection