routes/admin.php
<?php

use App\Http\Controllers\Admin\BlogsController;
use App\Http\Controllers\Admin\BookingsController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\FaqsController;
use App\Http\Controllers\Admin\InquiresController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\PackageCategoriesController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\ScheduleController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function () {
    Auth::routes();

    Route::post('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::get('/profile', [App\Http\Controllers\HomeController::class, 'profile'])->name('profile')->middleware('auth');

    Route::resource('locations', LocationController::class)->middleware('auth');
    Route::resource('cms', CmsController::class)->middleware('auth');
    Route::resource('faqs', FaqsController::class)->middleware('auth');
    Route::resource('inquires', InquiresController::class)->middleware('auth');
    Route::resource('package_categories', PackageCategoriesController::class)->middleware('auth');
    Route::resource('packages', PackagesController::class)->middleware('auth');
    Route::resource('schedule', ScheduleController::class)->middleware('auth');
    Route::resource('bookings', BookingsController::class)->middleware('auth');
    Route::resource('blogs', BlogsController::class)->middleware('auth');

    Route::post('fetch-states', [LocationController::class, 'fetchState'])->middleware('auth');
    Route::post('fetch-cities', [LocationController::class, 'fetchCity'])->middleware('auth');

    Route::get('slug', [CmsController::class, 'slug'])->name('slug')->middleware('auth');

    Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password')->middleware('auth');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

resources/views/admin/footer.blade.php
<footer class="footer">
    <div class="container">
      <div class="text-center">
        Copyright © {{ date("Y") }} Gold Star Driving
      </div>
    </div>
</footer>

resources/views/admin/header_bar.blade.php
<header class="topbar-nav">
    <nav class="navbar navbar-expand fixed-top">
     <ul class="navbar-nav mr-auto align-items-center">
       <li class="nav-item">
         <a class="nav-link toggle-menu" href="javascript:void();">
          <i class="icon-menu menu-icon"></i>
        </a>
       </li>
       {{-- <li class="nav-item">
         <form class="search-bar">
           <input type="text" class="form-control" placeholder="Enter keywords">
            <a href="javascript:void();"><i class="icon-magnifier"></i></a>
         </form>
       </li> --}}
     </ul>
        
     <ul class="navbar-nav align-items-center right-nav-link">
       {{-- <li class="nav-item dropdown-lg">
         <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
         <i class="fa fa-envelope-open-o"></i></a>
       </li>
       <li class="nav-item dropdown-lg">
         <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
         <i class="fa fa-bell-o"></i></a>
       </li>
       <li class="nav-item language">
         <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();"><i class="fa fa-flag"></i></a>
         <ul class="dropdown-menu dropdown-menu-right">
             <li class="dropdown-item"> <i class="flag-icon flag-icon-gb mr-2"></i> English</li>
             <li class="dropdown-item"> <i class="flag-icon flag-icon-fr mr-2"></i> French</li>
             <li class="dropdown-item"> <i class="flag-icon flag-icon-cn mr-2"></i> Chinese</li>
             <li class="dropdown-item"> <i class="flag-icon flag-icon-de mr-2"></i> German</li>
           </ul>
       </li> --}}
       <li class="nav-item">
         <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
           <span class="user-profile"><img src="https://ui-avatars.com/api/?name={{ \Auth::user()->name }}" class="img-circle" alt="user avatar"></span>
         </a>
         <ul class="dropdown-menu dropdown-menu-right">
          <li class="dropdown-item user-details">
           <a href="javaScript:void();">
              <div class="media">
                <div class="avatar"><img class="align-self-start mr-3" src="https://ui-avatars.com/api/?name={{ \Auth::user()->name }}" alt="user avatar"></div>
               <div class="media-body">
               <h6 class="mt-2 user-title">{{ \Auth::user()->name }}</h6>
               <p class="user-subtitle">{{ \Auth::user()->email }}</p>
               </div>
              </div>
             </a>
           </li>
           {{-- <li class="dropdown-divider"></li>
           <li class="dropdown-item"><i class="icon-wallet mr-2"></i> Account</li> --}}
           <li class="dropdown-divider"></li>
           <a href="{{ route('profile') }}"><li class="dropdown-item"><i class="icon-settings mr-2"></i> Setting</li></a>
           <li class="dropdown-divider"></li>
           <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><li class="dropdown-item"><i class="icon-power mr-2"></i> Logout</li></a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">@csrf</form>
         </ul>
       </li>
     </ul>
   </nav>
</header>

resources/views/admin/sidebar.blade.php
<!--Start sidebar-wrapper-->
<div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
    <div class="brand-logo">
     <a href="{{ route('home') }}">
      <img src="{{ asset('admin/assets/images/logo_star.webp') }}" class="logo-icon" alt="logo icon">
      <h5 class="logo-text">Gold Star Driving</h5>
    </a>
  </div>
  <ul class="sidebar-menu do-nicescrol">
        {{-- <li class="sidebar-header">MAIN NAVIGATION</li> --}}
        <li>
            <a href="{{ route('home') }}">
                <i class="zmdi zmdi-view-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'locations') ? 'active' : '' }}">
            <a href="{{ route('locations.index') }}">
                <i class="fa-sharp fa-solid fa-map-location-dot"></i> <span>Location</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'schedule') ? 'active' : '' }}">
            <a href="{{ route('schedule.index') }}">
                <i class="fa fa-server" aria-hidden="true"></i> <span>Schedule Management</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'bookings') ? 'active' : '' }}">
            <a href="{{ route('bookings.index') }}">
                <i class="fa fa-calendar-check-o" aria-hidden="true"></i> <span>Bookings</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'inquires') ? 'active' : '' }}">
            <a href="{{ route('inquires.index') }}">
                <i class="fa fa-phone-square" aria-hidden="true"></i> <span>Inquires</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'package_categories') ? 'active' : '' }}">
            <a href="{{ route('package_categories.index') }}">
                <i class="fa fa-list-alt" aria-hidden="true"></i> <span>Package Categories</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'packages') ? 'active' : '' }}">
            <a href="{{ route('packages.index') }}">
                <i class="fa fa-usd" aria-hidden="true"></i> <span>Packages</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'cms') ? 'active' : '' }}">
            <a href="{{ route('cms.index') }}">
                <i class="fa fa-cogs" aria-hidden="true"></i> <span>CMS</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'faqs') ? 'active' : '' }}">
            <a href="{{ route('faqs.index') }}">
                <i class="fa fa-question" aria-hidden="true"></i> <span>FAQs</span>
            </a>
        </li>
        <li class="{{ (request()->segment(2) == 'blogs') ? 'active' : '' }}">
            <a href="{{ route('blogs.index') }}">
                <i class="fa fa-rss-square" aria-hidden="true"></i> <span>Blogs</span>
            </a>
        </li>
   </ul>
  
  </div>
  <!--End sidebar-wrapper-->