routes/admin.php
<?php

use App\Http\Controllers\Admin\BlogsController;
use App\Http\Controllers\Admin\BookingsController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\FaqsController;
use App\Http\Controllers\Admin\InquiresController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\PackageCategoriesController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\ScheduleController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function () {
    Auth::routes();

    Route::post('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::get('/profile', [App\Http\Controllers\HomeController::class, 'profile'])->name('profile')->middleware('auth');

    Route::resource('locations', LocationController::class)->middleware('auth');
    Route::resource('cms', CmsController::class)->middleware('auth');
    Route::resource('faqs', FaqsController::class)->middleware('auth');
    Route::resource('inquires', InquiresController::class)->middleware('auth');
    Route::resource('package_categories', PackageCategoriesController::class)->middleware('auth');
    Route::resource('packages', PackagesController::class)->middleware('auth');
    Route::resource('schedule', ScheduleController::class)->middleware('auth');
    Route::resource('bookings', BookingsController::class)->middleware('auth');
    Route::resource('blogs', BlogsController::class)->middleware('auth');

    Route::post('fetch-states', [LocationController::class, 'fetchState'])->middleware('auth');
    Route::post('fetch-cities', [LocationController::class, 'fetchCity'])->middleware('auth');

    Route::get('slug', [CmsController::class, 'slug'])->name('slug')->middleware('auth');

    Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password')->middleware('auth');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Package.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Package extends Model
{
    use HasFactory;
    protected $fillable = ['package_categories_id', 'package_name', 'price', 'certification_fee', 'hst', 'total'];

    /**
     * Get the package category that owns the package.
     */
    public function packageCategory()
    {
        return $this->belongsTo(PackageCategory::class, 'package_categories_id', 'id');
    }

    /**
     * Get the package category that owns the package.
     */
    public function packageDetails()
    {
        return $this->hasMany(PackageDetail::class);
    }

    /**
     * belongs to location packages.
     */
    public function cityPackagePrice()
    {
        return $this->belongsTo(CityPackage::class, 'id', 'package_id');
    }
}

app/Http/Controllers/Admin/PackagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Package;
use App\Models\PackageCategory;
use App\Models\PackageDetail;
use Illuminate\Http\Request;

class PackagesController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $packages = Package::with(['packageCategory'])->orderBy('created_at', 'asc')->paginate(20);
        // dd($packages->toArray());
        return view('admin.Packages.index', compact('packages'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $packageCategories = PackageCategory::orderBy('title', 'asc')->get();
        return view('admin.Packages.create', compact('packageCategories'));
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        
        $request->validate([
            'package_categories_id' => 'required',
            'package_name' => 'required',
            'price' => 'required|between:0,999.99',
            'certification_fee' => 'required|between:0,999.99',
            'hst' => 'required|between:0,999.99'
        ]);
        try {
            $package = Package::create($request->post());
            if($package && !empty($request->pakcage_description)) {
                foreach($request->pakcage_description as $des) {
                    PackageDetail::create(['package_description' => $des, 'package_id' => $package->id]);
                }
            }
            return redirect()->route('packages.index')->with('success','package has been created successfully.');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\PackageCategory  $company
    * @return \Illuminate\Http\Response
    */
    public function edit(Package $package)
    {
        $packageCategories = PackageCategory::orderBy('title', 'asc')->get();
        return view('admin.Packages.edit',compact('package', 'packageCategories'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Package  $package
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Package $package)
    { 
        
        $request->validate([
            'package_categories_id' => 'required',
            'package_name' => 'required',
            'price' => 'required|between:0,999.99',
            'certification_fee' => 'required|between:0,999.99',
            'hst' => 'required|between:0,999.99'
        ]);
        try { 
            $package->fill($request->post())->save();
            if(!empty($request->pakcage_description)) {
                PackageDetail::where('package_id', $package->id)->delete();
                foreach($request->pakcage_description as $des) {
                    if(isset($des) && $des != null) {
                        PackageDetail::create(['package_description' => $des, 'package_id' => $package->id]);
                    }
                }
            }

            return redirect()->route('packages.index')->with('success','Package Has Been updated successfully');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Package  $package_category
    * @return \Illuminate\Http\Response
    */
    public function destroy(Package $package)
    {
        try {
            $package->delete();
            return redirect()->route('packages.index')->with('success','Package has been deleted successfully');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }
}

resources/views/admin/Packages/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="edit">
                            <h5>Create Package</h5><hr>
                            <form method="post" action="{{ route('packages.store') }}">
                                @csrf
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="package_categories_id">Package Category</label>
                                        <select id="package_categories_id" name="package_categories_id" class="form-control">
                                            <option value="" selected>Choose category...</option>
                                            @if(count($packageCategories) > 0)
                                                @foreach($packageCategories as $packageCategory)
                                                    <option value="{{ $packageCategory->id }}" {{ (old('package_categories_id') == $packageCategory->id ? "selected" : "") }}>{{ $packageCategory->title }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                        @if($errors->has('package_categories_id'))
                                            <div class="error"><b>{{ $errors->first('package_categories_id') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="package_name">Package Name</label>
                                        <input type="text" name="package_name" value="{{ old('package_name') }}" class="form-control" id="package_name" placeholder="Package Name">
                                        @if($errors->has('package_name'))
                                            <div class="error"><b>{{ $errors->first('package_name') }}</b></div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="price">Price</label>
                                        <input type="number" step="any" name="price" min="1" value="{{ old('price') }}" class="form-control" id="price" placeholder="Price">
                                        @if($errors->has('price'))
                                            <div class="error"><b>{{ $errors->first('price') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="certification_fee">Certification Fee</label>
                                        <input type="number" step="any" name="certification_fee" min="1" value="{{ old('certification_fee') }}" class="form-control" id="certification_fee" placeholder="Certification Fee">
                                        @if($errors->has('certification_fee'))
                                            <div class="error"><b>{{ $errors->first('certification_fee') }}</b></div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="hst">HST</label>
                                        <input type="number" step="any" name="hst" min="1" value="{{ old('hst') }}" class="form-control" id="hst" placeholder="HST">
                                        @if($errors->has('hst'))
                                            <div class="error"><b>{{ $errors->first('hst') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="total">Total</label>
                                        <input type="text" name="total" value="{{ old('total') }}" class="form-control" id="total" placeholder="Total" readonly>
                                        @if($errors->has('total'))
                                            <div class="error"><b>{{ $errors->first('total') }}</b></div>
                                        @endif
                                    </div>
                                </div><br><br>

                                <h5>Package Details</h5><hr>
                                <div class="package_description_section">
                                    <div class="form-row">
                                        <div class="form-group col-md-10">
                                            <label for="pakcage_description">Description</label>
                                            <input type="text" name="pakcage_description[]" class="form-control" placeholder="Pakcage Description">
                                            @if($errors->has('pakcage_description'))
                                                <div class="error"><b>{{ $errors->first('pakcage_description') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="col-md-2 add_more_button">
                                            <a href="#" class="btn btn-warning add_more">+</a>
                                        </div>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Save</button>
                                <a type="button" href="{{ route('packages.index') }}" class="btn btn-danger">Back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('custom_js')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $(".add_more").click(function() {
            $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });
            $(".package_description_section").append(`<div class="form-row required_inp">
                <div class="form-group col-md-10">
                    <label for="pakcage_description">Description</label>
                    <input type="text" name="pakcage_description[]" class="form-control" placeholder="Pakcage Description">
                    @if($errors->has('pakcage_description'))
                        <div class="error"><b>{{ $errors->first('pakcage_description') }}</b></div>
                    @endif
                </div>
                <div class="col-md-2 inputRemove_button">
                    <a href="#" class="btn btn-danger inputRemove">-</a>
                </div>
            </div>`);
        });
        $('body').on('click','.inputRemove',function() {
            $(this).closest('.required_inp').remove()
        });

        $('body').on('keyup','#price, #certification_fee, #hst',function() {
            let price = $("#price").val();
            let certification_fee = $("#certification_fee").val();
            let hst = $("#hst").val();
            $("#total").val(parseFloat(Number(price)+Number(certification_fee)+Number(hst)).toFixed(2));
        });
    });
</script>
@endsection

resources/views/admin/Packages/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="edit">
                            <h5>Update Package</h5><hr>
                            <form method="post" action="{{ route('packages.update', $package->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="package_categories_id">Package Category</label>
                                        <select id="package_categories_id" name="package_categories_id" class="form-control">
                                            <option value="" selected>Choose category...</option>
                                            @if(count($packageCategories) > 0)
                                                @foreach($packageCategories as $packageCategory)
                                                    <option value="{{ $packageCategory->id }}" {{ ($packageCategory->id == $package->packageCategory['id'] ? "selected" : "") }}>{{ $packageCategory->title }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                        @if($errors->has('package_categories_id'))
                                            <div class="error"><b>{{ $errors->first('package_categories_id') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="package_name">Package Name</label>
                                        <input type="text" name="package_name" value="{{ $package->package_name }}" class="form-control" id="package_name" placeholder="Package Name">
                                        @if($errors->has('package_name'))
                                            <div class="error"><b>{{ $errors->first('package_name') }}</b></div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="price">Price</label>
                                        <input type="number" step="any" name="price" value="{{ $package->price }}" class="form-control" id="price" placeholder="Price">
                                        @if($errors->has('price'))
                                            <div class="error"><b>{{ $errors->first('price') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="certification_fee">Certification Fee</label>
                                        <input type="number" step="any" name="certification_fee" value="{{ $package->certification_fee }}" class="form-control" id="certification_fee" placeholder="Certification Fee">
                                        @if($errors->has('certification_fee'))
                                            <div class="error"><b>{{ $errors->first('certification_fee') }}</b></div>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="hst">HST</label>
                                        <input type="number" step="any" name="hst" value="{{ $package->hst }}" class="form-control" id="hst" placeholder="HST">
                                        @if($errors->has('hst'))
                                            <div class="error"><b>{{ $errors->first('hst') }}</b></div>
                                        @endif
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="total">Total</label>
                                        <input type="text" name="total" value="{{ $package->total }}" class="form-control" id="total" placeholder="Total" readonly>
                                        @if($errors->has('total'))
                                            <div class="error"><b>{{ $errors->first('total') }}</b></div>
                                        @endif
                                    </div>
                                </div><br><br>

                                <h5>Package Details</h5><hr>
                                <div class="package_description_section">
                                    <div class="form-row">
                                        <div class="form-group col-md-10">
                                            <label for="pakcage_description">Description</label>
                                            <input type="text" name="pakcage_description[]" value="" class="form-control" id="pakcage_description" placeholder="Pakcage Description">
                                            @if($errors->has('pakcage_description'))
                                                <div class="error"><b>{{ $errors->first('pakcage_description') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="col-md-2 add_more_button">
                                            <a href="#" class="btn btn-warning add_more">+</a>
                                        </div>
                                    </div>

                                    @if(isset($package->packageDetails) && !empty($package->packageDetails))
                                        @foreach($package->packageDetails as $detail)
                                            <div class="form-row required_inp">
                                                <div class="form-group col-md-10">
                                                    <label for="pakcage_description">Description</label>
                                                    <input type="text" name="pakcage_description[]" value="{{ $detail->package_description }}" class="form-control" id="pakcage_description" placeholder="Pakcage Description">
                                                    @if($errors->has('pakcage_description'))
                                                        <div class="error"><b>{{ $errors->first('pakcage_description') }}</b></div>
                                                    @endif
                                                </div>
                                                <div class="col-md-2 inputRemove_button">
                                                    <a href="#" class="btn btn-danger inputRemove">-</a>
                                                </div>
                                            </div>
                                        @endforeach
                                    @endif
                                </div>

                                <button type="submit" class="btn btn-primary">Save</button>
                                <a type="button" href="{{ route('packages.index') }}" class="btn btn-danger">Back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('custom_js')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $(".add_more").click(function() {
            $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });
            $(".package_description_section").append(`<div class="form-row required_inp">
                <div class="form-group col-md-10">
                    <label for="pakcage_description">Description</label>
                    <input type="text" name="pakcage_description[]" class="form-control" id="pakcage_description" placeholder="Pakcage Description">
                    @if($errors->has('pakcage_description'))
                        <div class="error"><b>{{ $errors->first('pakcage_description') }}</b></div>
                    @endif
                </div>
                <div class="col-md-2 inputRemove_button">
                    <a href="#" class="btn btn-danger inputRemove">-</a>
                </div>
            </div>`);
        });
        $('body').on('click','.inputRemove',function() {
            $(this).closest('.required_inp').remove()
        });

        $('body').on('keyup','#price, #certification_fee, #hst',function() {
            let price = $("#price").val();
            let certification_fee = $("#certification_fee").val();
            let hst = $("#hst").val();
            $("#total").val(parseFloat(Number(price)+Number(certification_fee)+Number(hst)).toFixed(2));
        });
    });
</script>
@endsection

resources/views/admin/Packages/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row mt-3">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3"><h5 class="card-title">Packages</h5></div>
                            <div class="col-lg-9" style="padding: 15px"><a href="{{ route('packages.create') }}" class="btn btn-warning" style="float: right;">Create Package</a></div>
                        </div>
                        <div class="table-responsive">
                            <table class="table searchable_table">
                                <thead>
                                    <tr class="th_color">
                                        <th scope="col"><b>#</b></th>
                                        <th scope="col"><b>Package Category</b></th>
                                        <th scope="col"><b>Package</b></th>
                                        <th scope="col"><b>Price</b></th>
                                        <th scope="col"><b>Certification Fee</b></th>
                                        <th scope="col"><b>HST</b></th>
                                        <th scope="col"><b>Total</b></th>
                                        <th scope="col" style="text-align: end"><b>Action</b></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if(count($packages) > 0)
                                        @foreach($packages as $package)
                                            <tr>
                                                <th scope="row">{{ $package->id }}</th>
                                                <td>{{ $package->packageCategory['title'] ?? "" }}</td>
                                                <td>{{ $package->package_name ?? "" }}</td>
                                                <td>{{ $package->price ?? "" }}</td>
                                                <td>{{ $package->certification_fee ?? "" }}</td>
                                                <td>{{ $package->hst ?? "" }}</td>
                                                <td>{{ $package->total ?? "" }}</td>
                                                <td style="text-align: end">
                                                    <form action="{{ route('packages.destroy',$package->id) }}" method="Post">
                                                        <a class="btn btn-primary" href="{{ route('packages.edit',$package->id) }}">Edit</a>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('Do you want to delete this package?')" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <th scope="row"></th>
                                            <td></td>
                                            <td></td>
                                            <td>No Package Found!...</td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div style="padding: 15px">{{ $packages->links() }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection