routes/admin.php
<?php

use App\Http\Controllers\Admin\BlogsController;
use App\Http\Controllers\Admin\BookingsController;
use App\Http\Controllers\Admin\CmsController;
use App\Http\Controllers\Admin\FaqsController;
use App\Http\Controllers\Admin\InquiresController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\PackageCategoriesController;
use App\Http\Controllers\Admin\PackagesController;
use App\Http\Controllers\Admin\ScheduleController;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web']], function () {
    Auth::routes();

    Route::post('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::get('/profile', [App\Http\Controllers\HomeController::class, 'profile'])->name('profile')->middleware('auth');

    Route::resource('locations', LocationController::class)->middleware('auth');
    Route::resource('cms', CmsController::class)->middleware('auth');
    Route::resource('faqs', FaqsController::class)->middleware('auth');
    Route::resource('inquires', InquiresController::class)->middleware('auth');
    Route::resource('package_categories', PackageCategoriesController::class)->middleware('auth');
    Route::resource('packages', PackagesController::class)->middleware('auth');
    Route::resource('schedule', ScheduleController::class)->middleware('auth');
    Route::resource('bookings', BookingsController::class)->middleware('auth');
    Route::resource('blogs', BlogsController::class)->middleware('auth');

    Route::post('fetch-states', [LocationController::class, 'fetchState'])->middleware('auth');
    Route::post('fetch-cities', [LocationController::class, 'fetchCity'])->middleware('auth');

    Route::get('slug', [CmsController::class, 'slug'])->name('slug')->middleware('auth');

    Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password')->middleware('auth');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Schedule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    use HasFactory;
    protected $fillable = ['year', 'month', 'date', 'days', 'time'];
}

app/Http/Controllers/Admin/ScheduleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Schedule;
use Illuminate\Http\Request;

class ScheduleController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $schedules = Schedule::orderBy('created_at', 'desc')->paginate(20);
        return view('admin.Schedules.index', compact('schedules'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        return view('admin.Schedules.create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'year.*' => 'required',
                'month.*' => 'required',
                'date.*' => 'required',
                'days.*' => 'required',
                'time.*' => 'required'
            ]);
            if($request->year && !empty($request->year)){
                foreach($request->year as $key => $scheduleData){
                    Schedule::create([
                        'year' => $scheduleData,
                        'month' => $request->month[$key],
                        'date' => $request->date[$key],
                        'days' => $request->days[$key],
                        'time' => $request->time[$key],
                    ]);
                }
            }
            
            return redirect()->route('schedule.index')->with('success','Schedule has been created successfully.');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Schedule $schedule
    * @return \Illuminate\Http\Response
    */
    public function edit(Schedule $schedule)
    {
        return view('admin.Schedules.edit',compact('schedule'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Schedule  $schedule
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Schedule $schedule)
    {
        try {
            $request->validate([
                'year' => 'required',
                'month' => 'required',
                'date' => 'required',
                'days' => 'required',
                'time' => 'required'
            ]);
            
            $schedule->fill($request->post())->save();

            return redirect()->route('schedule.index')->with('success','Schedule Has Been updated successfully');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Schedule  $schedule
    * @return \Illuminate\Http\Response
    */
    public function destroy(Schedule $schedule)
    {
        try {
            $schedule->delete();
            return redirect()->route('schedule.index')->with('success','Schedule has been deleted successfully');
        } catch(\Exception $ex) {
            return redirect()->back()->with('error',$ex->getMessage());
        }
    }
}

resources/views/admin/Schedules/create.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="edit">
                            <h5>Create Schedule</h5><hr>
                            <form method="post" action="{{ route('schedule.store') }}">
                                @csrf
                                <div class="schedule_section">
                                    <div class="form-row" style="border: 1px solid greenyellow; padding: 5px; margin-bottom: 10px;">
                                        <div class="form-group col-md-3">
                                            <label for="year">Year</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input data-date-format="yyyy" name="year[]" class="form-control datepicker">
                                            @if($errors->has('year'))
                                                <div class="error"><b>{{ $errors->first('year') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="month">Month</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input data-date-format="mm" name="month[]" class="form-control datepicker1">
                                            @if($errors->has('month'))
                                                <div class="error"><b>{{ $errors->first('month') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label for="date">Date</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input type="text" id="date" name="date[]" class="form-control">
                                            @if($errors->has('date'))
                                                <div class="error"><b>{{ $errors->first('date') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label for="days">Days</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input type="text" id="days" name="days[]" class="form-control">
                                            @if($errors->has('days'))
                                                <div class="error"><b>{{ $errors->first('days') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-5">
                                            <label for="time">Time</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input type="text" id="time" name="time[]" class="form-control">
                                            @if($errors->has('time'))
                                                <div class="error"><b>{{ $errors->first('time') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-1 add_more_button">
                                            <a href="#" class="btn btn-warning add_more">+</a>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a type="button" href="{{ route('schedule.index') }}" class="btn btn-danger">Back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content');
</script>
    @section('custom_js')
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script> 
        <script type="text/javascript">
            let selectedYear = "";
            let thisYear = new Date().getFullYear();
            $(document).on('change',".datepicker", function(){
                selectedYear = $(this).val();
            });

            $(document).on('focus',".datepicker", function(){
                $(this).blur();
                $('.datepicker').datepicker({
                    autoclose: true,
                    format: "yyyy",
                    viewMode: "years",
                    minViewMode: "years",
                    startDate: new Date()
                });
            });
            $(document).on('focus',".datepicker1", function(){
                $('.datepicker1').datepicker({
                    autoclose: true,
                    format: "MM",
                    viewMode: "months",
                    minViewMode: "months",
                    startDate: selectedYear > thisYear ? new Date(selectedYear+"-01-01") : new Date()
                });
            });
            $(document).ready(function() {
                $(".add_more").on('click', function() {
                    $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });
                    $(".schedule_section").append(`<div class="form-row required_inp" style="border: 1px solid greenyellow; padding: 5px; margin-bottom: 10px;">
                        <div class="form-group col-md-3">
                            <label for="year">Year</label>
                            <input data-date-format="yyyy" name="year[]" class="form-control datepicker">
                            @if($errors->has('year'))
                                <div class="error"><b>{{ $errors->first('year') }}</b></div>
                            @endif
                        </div>
                        <div class="form-group col-md-3">
                            <label for="month">Month</label>
                            <input data-date-format="mm" name="month[]" class="form-control datepicker1">
                            @if($errors->has('month'))
                                <div class="error"><b>{{ $errors->first('month') }}</b></div>
                            @endif
                        </div>
                        <div class="form-group col-md-6">
                            <label for="date">Date</label>
                            <input type="text" id="date" name="date[]" class="form-control">
                            @if($errors->has('date'))
                                <div class="error"><b>{{ $errors->first('date') }}</b></div>
                            @endif
                        </div>
                        <div class="form-group col-md-6">
                            <label for="days">Days</label>
                            <input type="text" id="days" name="days[]" class="form-control">
                            @if($errors->has('days'))
                                <div class="error"><b>{{ $errors->first('days') }}</b></div>
                            @endif
                        </div>
                        <div class="form-group col-md-5">
                            <label for="time">Time</label>
                            <input type="text" id="time" name="time[]" class="form-control">
                            @if($errors->has('time'))
                                <div class="error"><b>{{ $errors->first('time') }}</b></div>
                            @endif
                        </div>
                        <div class="form-group col-md-1 inputRemove_button">
                            <a href="#" class="btn btn-danger inputRemove">-</a>
                        </div>
                    </div>`);
                });

                $('body').on('click','.inputRemove',function() {
                    $(this).closest('.required_inp').remove()
                });
            });

            

        </script>
    @endsection
@endsection

resources/views/admin/Schedules/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="edit">
                            <h5>Update Schedule</h5><hr>
                            <form method="post" action="{{ route('schedule.update', $schedule->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="schedule_section">
                                    <div class="form-row" style="border: 1px solid greenyellow; padding: 5px; margin-bottom: 10px;">
                                        <div class="form-group col-md-3">
                                            <label for="year">Year</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input data-date-format="yyyy" id="datepicker" value="{{ $schedule->year }}" name="year" class="form-control datepicker">
                                            @if($errors->has('year'))
                                                <div class="error"><b>{{ $errors->first('year') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="month">Month</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input data-date-format="mm" id="datepicker1" value="{{ $schedule->month }}" name="month" class="form-control datepicker1">
                                            @if($errors->has('month'))
                                                <div class="error"><b>{{ $errors->first('month') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label for="date">Date</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input type="text" id="date" name="date" value="{{ $schedule->date }}" class="form-control">
                                            @if($errors->has('date'))
                                                <div class="error"><b>{{ $errors->first('date') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label for="days">Days</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input type="text" id="days" name="days" value="{{ $schedule->days }}" class="form-control">
                                            @if($errors->has('days'))
                                                <div class="error"><b>{{ $errors->first('days') }}</b></div>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label for="time">Time</label>
                                            {{-- <input type="text" name="title" value="{{ old('title') }}" class="form-control" id="title" placeholder="Title"> --}}
                                            <input type="text" id="time" name="time" value="{{ $schedule->time }}" class="form-control">
                                            @if($errors->has('time'))
                                                <div class="error"><b>{{ $errors->first('time') }}</b></div>
                                            @endif
                                        </div>
                                        {{-- <div class="form-group col-md-1 add_more_button">
                                            <a href="#" class="btn btn-warning add_more">+</a>
                                        </div> --}}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                                <a type="button" href="{{ route('schedule.index') }}" class="btn btn-danger">Back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    CKEDITOR.replace('content');
</script>
@endsection

@section('custom_js')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">

    let selectedYear = "";
    let thisYear = new Date().getFullYear();
    $(document).on('change',".datepicker", function(){
        selectedYear = $(this).val();
    });

    $(document).on('focus',".datepicker", function(){
        $(this).blur();
        $('.datepicker').datepicker({
            autoclose: true,
            format: "yyyy",
            viewMode: "years",
            minViewMode: "years",
            startDate: new Date()
        });
    });

    $(document).on('focus',".datepicker1", function(){
        $('.datepicker1').datepicker({
            autoclose: true,
            format: "MM",
            viewMode: "months",
            minViewMode: "months",
            // startDate: new Date()
            startDate: selectedYear > thisYear ? new Date(selectedYear+"-01-01") : new Date()
        });
    });

</script>
@endsection

resources/views/admin/Schedules/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="row mt-3">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3"><h5 class="card-title">Schedules</h5></div>
                            <div class="col-lg-9" style="padding: 15px"><a href="{{ route('schedule.create') }}" class="btn btn-warning" style="float: right;">Create Schedule</a></div>
                        </div>
                        <div class="table-responsive">
                            <table class="table searchable_table">
                                <thead>
                                    <tr class="th_color">
                                        <th scope="col"><b>#</b></th>
                                        <th scope="col"><b>Year & Month</b></th>
                                        <th scope="col"><b>Date</b></th>
                                        <th scope="col"><b>Days</b></th>
                                        <th scope="col"><b>Time</b></th>
                                        <th scope="col"><b>Action</b></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if(count($schedules) > 0)
                                        @foreach($schedules as $schedule)
                                            <tr>
                                                <th scope="row">{{ $schedule->id }}</th>
                                                <td>{{ $schedule->year . " " . $schedule->month ?? "" }}</td>
                                                <td>{{ $schedule->date ?? "" }}</td>
                                                <td>{{ $schedule->days ?? "" }}</td>
                                                <td>{{ $schedule->time ?? "" }}</td>
                                                <td>
                                                    <form action="{{ route('schedule.destroy',$schedule->id) }}" method="Post">
                                                        <a class="btn btn-primary" href="{{ route('schedule.edit',$schedule->id) }}">Edit</a>
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('Do you want to delete this schedule?')" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <th scope="row"></th>
                                            <td></td>
                                            <td></td>
                                            <td>No schedules Found!...</td>
                                            <td></td>
                                        </tr>
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div style="padding: 15px">{{ $schedules->links() }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection